/**
 * sound.js — UI notification sounds.
 *
 * WHAT WAS WRONG BEFORE
 * ─────────────────────
 * The project had NO notification sound at all. The only audio it could make
 * was the Web Speech API pronunciation in `speech.js`, which was tuned to
 * `pitch: 0.85` ("deeper = male character") at `volume: 1` and deliberately
 * preferred deep male voices. On any device whose available local voices are
 * low-quality synths (eSpeak / Flite "compact" voices — very common on Linux
 * and Android), that combination is read as a low, distorted, growl-like
 * "horror" tone. That module is now tuned neutrally; this file adds the
 * clean notification sound the app was missing.
 *
 * HOW THIS WORKS
 * ──────────────
 * Four short, soft, pure-sine WAV files generated by
 * `client/scripts/generate_sounds.js` (130-245 ms each, peak-normalised to
 * 0.62 so they can never clip). They are played through ONE lazily-created
 * `HTMLAudioElement` per sound, created on first use and reused for the whole
 * session — never per render, never more than one element per sound.
 *
 * THE RULES THIS FILE ENFORCES
 *   • Autoplay policy: nothing is ever created or played before the user has
 *     interacted with the page. A one-time pointerdown/keydown listener marks
 *     the session as unlocked; until then `playSound()` is a silent no-op.
 *   • No stacking: the same sound cannot replay within MIN_REPLAY_MS, and
 *     each sound keeps at most ONE element, so repeated notifications never
 *     overlap into distortion.
 *   • Moderate volume: VOLUME is capped well below 1.0.
 *   • Failure is silent and harmless: a missing/corrupt file disables that
 *     one sound permanently and never throws, never spams the console, and
 *     never blocks the UI action that triggered it.
 *   • Debounced duplicates: two identical sounds in the same tick play once.
 */

const SOUND_FILES = {
  success: '/sounds/success.wav',
  notify: '/sounds/notify.wav',
  warning: '/sounds/warning.wav',
  error: '/sounds/error.wav',
};

/* Moderate by design. The tones are already peak-limited to 0.62 in the file,
   so even at full volume there is headroom before any clipping. */
const VOLUME = 0.28;

/* Ignore a repeat of the SAME sound inside this window (ms). Prevents a burst
   of identical notifications from stacking into a loud, distorted mess. */
const MIN_REPLAY_MS = 700;

/* Only a small, allow-listed set of meanings may ever make a sound. Anything
   else (info toasts, hover states, renders) is silent by construction. */
export const SOUND = {
  SUCCESS: 'success',
  WARNING: 'warning',
  ERROR: 'error',
  SCAN: 'notify',
};

const isBrowser = typeof window !== 'undefined';

/* name -> { el, failed, lastPlayed } */
const players = new Map();
let unlocked = false;
const recent = new Map();
let muted = false;

try {
  muted = isBrowser && window.localStorage.getItem('pharm_sound_muted') === '1';
} catch (_) { muted = false; }

const unlock = () => {
  if (!isBrowser || unlocked) return;
  unlocked = true;
  ['pointerdown', 'keydown', 'touchstart'].forEach((evt) => {
    window.removeEventListener(evt, unlock);
  });
};

/* The FIRST real interaction unlocks audio for the whole session. This is
   what satisfies the browser autoplay policy: before this fires, playSound()
   is a guaranteed no-op and no Audio element is ever constructed. */
if (isBrowser) {
  ['pointerdown', 'keydown', 'touchstart'].forEach((evt) => {
    window.addEventListener(evt, unlock, { once: true, passive: true });
  });
}

/**
 * Get (and lazily create) the single audio element for a sound.
 * Returns null when audio is unavailable or the file failed to load.
 */
const getPlayer = (name) => {
  const src = SOUND_FILES[name];
  if (!src) return null;

  const existing = players.get(name);
  if (existing) return existing.failed ? null : existing.el;
  if (!isBrowser || typeof Audio === 'undefined') return null;

  const entry = { el: null, failed: false, lastPlayed: 0 };
  try {
    const el = new Audio(src);
    el.preload = 'auto';
    el.volume = VOLUME;

    /* A missing or undecodable file must never surface as an error to the
       user: mark this one sound unavailable and stop retrying, silently. */
    el.addEventListener('error', () => { entry.failed = true; });
    el.addEventListener('stalled', () => { entry.failed = true; });

    entry.el = el;
  } catch (_) {
    entry.failed = true;
  }

  players.set(name, entry);
  return entry.failed ? null : entry.el;
};

/**
 * Play a notification sound.
 * @param {string} name  one of SOUND.*
 * @param {object} [opts]
 * @param {string} [opts.dedupeKey]  identical keys within ~120ms play once.
 * @returns {boolean} whether audio was actually started.
 */
export const playSound = (name, opts = {}) => {
  // Autoplay policy: no sound before the user has interacted with the page.
  if (!unlocked || muted) return false;

  const now = Date.now();
  const key = opts.dedupeKey || name;

  // Collapse simultaneous duplicates (double-submit, several toasts in a tick).
  if (now - (recent.get(key) || 0) < 120) return false;
  // And never let one sound overlap itself.
  const entry = players.get(name);
  if (entry && now - entry.lastPlayed < MIN_REPLAY_MS) return false;
  recent.set(key, now);

  const el = getPlayer(name);
  if (!el) return false;

  try {
    el.currentTime = 0;
    el.volume = VOLUME;
    const result = el.play();
    if (result && typeof result.catch === 'function') {
      // Autoplay rejection: stay silent rather than log an unhandled error.
      result.catch(() => {});
    }
    if (entry) entry.lastPlayed = now;
    return true;
  } catch (_) {
    return false;
  }
};

/** Map a toast type to a sound. `info` is intentionally silent. */
export const soundForToast = (type) => {
  if (type === 'success') return SOUND.SUCCESS;
  if (type === 'warning') return SOUND.WARNING;
  if (type === 'error') return SOUND.ERROR;
  return null;
};

/** Sound for an accepted barcode / QR scan. */
export const playScanSound = () => playSound(SOUND.SCAN);

export const isMuted = () => muted;

export const setMuted = (value) => {
  muted = Boolean(value);
  try { window.localStorage.setItem('pharm_sound_muted', muted ? '1' : '0'); } catch (_) { /* ignore */ }
  if (muted) stopAllSounds();
  return muted;
};

export const toggleMuted = () => setMuted(!muted);

/** Immediately silence anything currently playing (used when muting / hiding). */
export const stopAllSounds = () => {
  players.forEach((entry) => {
    if (!entry.el) return;
    try { entry.el.pause(); entry.el.currentTime = 0; } catch (_) { /* ignore */ }
  });
};

/**
 * Warm the sound files up (after the first user interaction) so the very first
 * notification is not delayed by a fetch. Failures stay silent.
 */
export const preloadSounds = () => {
  Object.keys(SOUND_FILES).forEach((name) => {
    const el = getPlayer(name);
    if (el && typeof el.load === 'function') {
      try { el.load(); } catch (_) { /* ignore */ }
    }
  });
};

/* Warm the cache as soon as the browser reports the session is unlocked. */
if (isBrowser) {
  ['pointerdown', 'keydown', 'touchstart'].forEach((evt) => {
    window.addEventListener(evt, () => { if (unlocked) preloadSounds(); }, { once: true, passive: true });
  });
  // Stop sounds when the tab is hidden — nobody wants a pharmacy counter
  // chime firing from a background tab.
  document.addEventListener('visibilitychange', () => {
    if (document.hidden) stopAllSounds();
  });
}

